### ISSUE TITLE
Generated keystore file probably invalid

### ISSUE THREAD

**Issue by hbarcelos** [kyledewy/eth-keys#2]
When generating a keystore file from a private key, I end up with something like:

```
{
  "address": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "version": 3,
  "Crypto": {
    "cipher": "aes-128-ctr",
    "cipherparams": {
      "iv": "00000000000000000000000000000000"
    },
    "ciphertext": "0000000000000000000000000000000000000000000000000000000000000000",
    "kdf": "scrypt",
    "kdfparams": {
      "salt": "0000000000000000000000000000000000000000000000000000000000000000",
      "n": 131072,
      "dklen": 32,
      "p": 1,
      "r": 8
    },
    "mac": "0000000000000000000000000000000000000000000000000000000000000000"
  }
}
```

However the `"Crypto"` key is usually lowercase when generating it with other tools.

This makes the generated file invalid to be used with [Foundry](https://github.com/foundry-rs/foundry) for example.

**Comment by 0xdewy** [comment]
Hey thanks for the heads up. I added the lower-case `crypto` field as a band-aid fix for now. I believe ethersjs is updating this so I will update ethersjs dependency once that is stable.
